apiVersion: backstage.io/v1alpha1
{%- if values.entityKind %}
kind: ${{ values.entityKind }}
{%- else %}
kind: Component
{%- endif %}
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    argocd/app-selector: rht-gitops.com/janus-argocd=${{values.component_id}}-bootstrap
    backstage.io/kubernetes-id: ${{values.component_id}}
    janus-idp.io/tekton: ${{values.component_id}}
    backstage.io/source-location: url:https://${{values.host}}/${{values.destination}}
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: ${{values.destination}}
    quay.io/repository-slug: ${{values.quay_destination | dump}}
  tags:
    - dotnet
  links:
    - url: https://devspaces${{values.cluster}}/#https://${{values.host}}/${{values.destination}}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service # remove hardcoded value
  # system: ${{ values.system }}
  lifecycle: production
  owner: "user1" # remove hardcoded value
  {%- if values.dependsOn %}
  dependsOn:
    - ${{ values.dependsOn }}
  {%- endif %}
  {%- if values.partOf %}
  partOf:
    - ${{ values.partOf }}
  {%- endif %}

